Push button routine, more cleanups
danielbernalb/LibreCO2 pull request #8
Opened 2021-02-25 21:12 UTC by kyogithub

2021-02-25 23:46 UTC, danielbernalb commented on LibreCO2_SCD30/LibreCO2_SCD30_ArduinoUNO.ino
> +        display.print("CAL-");
The CAL- message only be showed by 100ms, not 5 seconds like before:
delay(5000);

2021-02-25 23:48 UTC, danielbernalb commented on LibreCO2_SCD30/LibreCO2_SCD30_ArduinoUNO.ino
> -  delay (3000);
The HEAT message not showed, the delay of 3000 seconds was deleted but not replaced

2021-02-25 23:49 UTC, danielbernalb requested changes
Two delays deleted but not replaced, messages desapears

2021-02-26 19:00 UTC, kyogithub reviewed
Delays distributed

2021-02-27 02:09 UTC, merged